### PR TITLE
Increase Node requirement from 18 to 20 (current LTS)

### PR DESCRIPTION
**Pull request by mattbrictson**

### CODE REVIEW

**Comment by mattbrictson** [comment]
Looks like the default GitHub Actions runner still uses Node 18, so it is probably too soon to upgrade.

**Comment by park-jemin** [comment]
Bumping this - GitHub has `ubuntu-24.04` as the latest :)

**Comment by mattbrictson** [comment]
This announcement says regarding the change to `ubuntu-24.04` 

> This change will be rolled out over a period of several weeks beginning in September 25th, 2024. We plan to complete the migration by October 30th , 2024.

https://github.com/actions/runner-images/issues/10636

Just to be safe, I think I will wait until the October 30th date.

**Comment by mattbrictson** [comment]
The aforementioned https://github.com/actions/runner-images/issues/10636 has been updated with this note:

> NOTICE: THIS ROLLOUT HAS BEEN PUT ON HOLD

No explanation was given.

So I guess we will need to continue waiting on merging this PR.

**Comment by mattbrictson** [comment]
Instead of waiting for `ubuntu-latest` to be updated, I instead opted into `ubuntu-24.04` explicitly. This gives us the more recent version of Node. We're no longer blocked by the `ubuntu-latest` rollout.

**Pull request merged**
